spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zouxin
    password: M!33kobayashi
    url: jdbc:mysql://localhost:3306/diomall_sms
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000