spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zouxin
    password: M!33kobayashi
    url: jdbc:mysql://localhost:3306/diomall_ums
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: diomall-member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000

diomall:
  member:
    user:
      name: Kars
      age: 30000